package net.bewis09.bewisclient.util.color

import net.bewis09.bewisclient.game.translations.Translation
import net.bewis09.bewisclient.util.logic.ClientInterface
import net.bewis09.renderite.logic.color

val colors = listOf(
    TranslatedColor(0xFF0000, "red", "Red"),
    TranslatedColor(0x00FF00, "green", "Green"),
    TranslatedColor(0x0000FF, "blue", "Blue"),
    TranslatedColor(0xFFFF00, "yellow", "Yellow"),
    TranslatedColor(0x00FFFF, "cyan", "Cyan"),
    TranslatedColor(0xFF00FF, "magenta", "Magenta"),
    TranslatedColor(0xFFFFFF, "white", "White"),
    TranslatedColor(0x000000, "black", "Black"),
    TranslatedColor(0x808080, "gray", "Gray"),
    TranslatedColor(0x404040, "dark_gray", "Dark Gray"),
    TranslatedColor(0xC0C0C0, "light_gray", "Light Gray"),
    TranslatedColor(0xFFA500, "orange", "Orange"),
    TranslatedColor(0xFFC0CB, "pink", "Pink"),
    TranslatedColor(0x800080, "purple", "Purple"),
    TranslatedColor(0xA52A2A, "brown", "Brown"),
    TranslatedColor(0x00FF00, "lime", "Lime"),
    TranslatedColor(0x008080, "teal", "Teal"),
    TranslatedColor(0x000080, "navy", "Navy"),
    TranslatedColor(0x808000, "olive", "Olive"),
    TranslatedColor(0x800000, "maroon", "Maroon"),
    TranslatedColor(0xFFD700, "gold", "Gold"),
    TranslatedColor(0xC0C0C0, "silver", "Silver"),
    TranslatedColor(0x4B0082, "indigo", "Indigo"),
    TranslatedColor(0xEE82EE, "violet", "Violet"),
    TranslatedColor(0xFF7F50, "coral", "Coral"),
    TranslatedColor(0xFA8072, "salmon", "Salmon"),
    TranslatedColor(0xF0E68C, "khaki", "Khaki"),
    TranslatedColor(0xDDA0DD, "plum", "Plum"),
    TranslatedColor(0xDA70D6, "orchid", "Orchid"),
    TranslatedColor(0x40E0D0, "turquoise", "Turquoise"),
    TranslatedColor(0xDC143C, "crimson", "Crimson"),
    TranslatedColor(0xA0522D, "sienna", "Sienna"),
    TranslatedColor(0xD2691E, "chocolate", "Chocolate"),
    TranslatedColor(0xD2B48C, "tan", "Tan"),
    TranslatedColor(0xFFDAB9, "peach", "Peach"),
    TranslatedColor(0xE6E6FA, "lavender", "Lavender"),
    TranslatedColor(0x98FF98, "mint", "Mint"),
    TranslatedColor(0x87CEEB, "sky_blue", "Sky Blue"),
    TranslatedColor(0x00FFFF, "aqua", "Aqua"),
    TranslatedColor(0x228B22, "forest_green", "Forest Green"),
    TranslatedColor(0x4169E1, "royal_blue", "Royal Blue"),
    TranslatedColor(0xFF1493, "deep_pink", "Deep Pink"),
    TranslatedColor(0xB22222, "firebrick", "Firebrick"),
    TranslatedColor(0x4682B4, "steel_blue", "Steel Blue"),
    TranslatedColor(0x006400, "dark_green", "Dark Green"),
    TranslatedColor(0x8B0000, "dark_red", "Dark Red"),
    TranslatedColor(0x00008B, "dark_blue", "Dark Blue"),
    TranslatedColor(0xFF69B4, "hot_pink", "Hot Pink"),
    TranslatedColor(0x32CD32, "lime_green", "Lime Green"),
    TranslatedColor(0xFF4500, "orange_red", "Orange Red"),
    TranslatedColor(0x2E8B57, "sea_green", "Sea Green"),
    TranslatedColor(0x708090, "slate_gray", "Slate Gray"),
    TranslatedColor(0x9370DB, "medium_purple", "Medium Purple"),
    TranslatedColor(0xFF8C00, "dark_orange", "Dark Orange"),
    TranslatedColor(0xADD8E6, "light_blue", "Light Blue"),
    TranslatedColor(0x90EE90, "light_green", "Light Green"),
    TranslatedColor(0xFFB6C1, "light_pink", "Light Pink"),
    TranslatedColor(0xF5DEB3, "wheat", "Wheat"),
)

class TranslatedColor(color: Int, id: String, text: String): ClientInterface {
    val color = color.color
    val translation = Translation("color.$id", text)
}